Repository SCBJ-7/SCBJ-FE, pull requests merged in 2024-06, with the labels that each got.

#353 feat: 바텀 네비게이션 개선
  package-lock.json
  src/assets/icons/navIcon/icon_home_fill.svg
  src/assets/icons/navIcon/icon_home_line.svg
  src/assets/icons/navIcon/icon_my_fill.svg
  src/assets/icons/navIcon/icon_my_line.svg
  src/assets/icons/navIcon/icon_search_fill.svg
  src/assets/icons/navIcon/icon_search_line.svg
  src/assets/icons/navIcon/icon_transferWriting_fill.svg
  src/assets/icons/navIcon/icon_transferWriting_line.svg
  src/assets/icons/navIcon/icon_wish_fill.svg
  src/assets/icons/navIcon/icon_wish_line.svg
  src/components/layout/navBottom/NavBottom.style.ts
  src/components/layout/navBottom/NavBottom.tsx
  src/components/redirect/Redirect.tsx
  src/utils/getErrorMessage.ts
  svg.d.ts
  tsconfig.json
Labels: DESIGN

#358 HotFix: tsconfig 에러 처리 유연하게 변경
  tsconfig.json
Labels: FIX

#365 refactor: 사용하지 않는 spec 제거
  tests/e2eTests/specs/authentication/login.spec.ts
  tests/e2eTests/specs/authentication/register.spec.ts
Labels: REFACTOR

#367 HotFix: 상세페이지 로그인 상태 여부에 따른 클라이언트 변경
  src/apis/fetchRoom.ts
Labels: FIX
