Repository SCBJ-7/SCBJ-FE, pull requests merged in 2024-01, with the labels that each got.

#7 feat : firebase CICD 작업
  .firebaserc
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  firebase.json
Labels: FEAT

#13 [#9] issueTemplate, PRTemplate 수정 및 Readme.md 수정
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/design.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: DOCS, CHORE

#15 [#14] firebase pr preview 임시 비활성화
  .github/workflows/firebase-hosting-pull-request.yml
Labels: FIX

#20 [#16] 테스트 라이브러리 설정
  package-lock.json
  package.json
  playwright.config.ts
  tests/e2eTests/example.spec.ts
  tests/unitTestsSrc/example.test.ts
  tests/unitTestsSrc/setup.ts
  vite.config.ts
Labels: CHORE

#19 [#17] 반응형 디자인 전략 readme에 추가
  README.md
Labels: DOCS

#25 [#23] styled-component 삭제(잘못된 라이브러리)
  package-lock.json
  package.json
Labels: CHORE

#26 [#24] framer-motion 설치
  package-lock.json
  package.json
Labels: FEAT

#21 [#10] Feat: 페이지 및 라우팅 세팅
  src/App.tsx
  src/constants/path.ts
  src/main.tsx
  src/pages/detailPage/index.tsx
  src/pages/homePage/index.tsx
  src/pages/myPage/index.tsx
  src/pages/notFoundPage/index.tsx
  src/pages/searchPage/index.tsx
  src/pages/signInPage/index.tsx
  src/pages/signUpPage/index.tsx
  src/pages/transferPurchasePage/index.tsx
  src/pages/transferSalePage/index.tsx
  src/pages/transferWritingPage/index.tsx
  src/routes/router.tsx
Labels: FEAT

#28 [#27] GlobalStyle & Theme 외부 파일 생성
  src/main.tsx
  src/styles/globalStyle.ts
  src/styles/theme.ts
Labels: REFACTOR

#22 [#11] husky & lint-staged 로 commit 시 lint 검사 자동화
  .gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: CHORE

#32 [#30] firebase PR 코드 수정 및 playwright 테스트 코드 수정
  .github/workflows/firebase-hosting-pull-request.yml
  package-lock.json
  package.json
  src/pages/detailPage/index.tsx
  src/pages/homePage/index.tsx
  src/pages/myPage/index.tsx
  src/pages/notFoundPage/index.tsx
  src/pages/searchPage/index.tsx
  src/pages/signUpPage/index.tsx
  src/pages/transferPurchasePage/index.tsx
  src/pages/transferSalePage/index.tsx
  src/pages/transferWritingPage/index.tsx
  tests/e2eTests/example.spec.ts
Labels: FIX

#33 [#31] 최상위 컨테이너 설정
  package-lock.json
  src/App.css
  src/App.tsx
  src/components/.gitkeep
  src/components/layout/index.tsx
Labels: DESIGN

#36 [#35] path aliases 설정
  package-lock.json
  package.json
  tsconfig.json
  vite.config.ts
  vitest.config.ts
Labels: CHORE

#41 [#40] 사용하지 않는 파일 제거
  src/index.css
  src/main.tsx
Labels: CHORE

#38 [#29] msw 설정
  .husky/pre-commit
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/broswer.ts
  src/mocks/data/dummyRoom.json
  src/mocks/handler.ts
  src/pages/homePage/index.tsx
Labels: FEAT

#50 [#46] prettier 설정, 커밋 시 lint&prettier 검사 자동화
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  tsconfig.json
Labels: CHORE

#48 [#47] typography 파일을 theme 파일로 병합
  src/components/layout/navBottom/bottomNav.styled.ts
  src/styles/globalStyle.ts
  src/styles/theme.ts
  src/styles/typography.ts
Labels: DESIGN

#54 [#52] 양도글 작성 페이지 마크업, 더미데이터 연결, 모션 완료
  package-lock.json
  package.json
  src/apis/.gitkeep
  src/apis/fetchTransferItems.ts
  src/assets/icons/NavHome.tsx
  src/components/layout/Layout.style.ts
  src/components/layout/Layout.tsx
  src/components/layout/header/HeaderTop.tsx
  src/components/layout/navBottom/NavBottom.style.ts
  src/components/layout/navBottom/NavBottom.tsx
  src/constants/path.ts
  src/mocks/data/reservationList.json
  src/mocks/handler.ts
  src/pages/transerWritingPricePage/TransferWritingPrice.style.ts
  src/pages/transerWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPage/TransferWriting.style.ts
  src/pages/transferWritingPage/TransferWriting.styled.ts
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPage/transferItem/TransferItem.style.ts
  src/pages/transferWritingPage/transferItem/TransferItem.tsx
  src/pages/transferWritingPage/transferItemList/TransferItemList.style.ts
  src/pages/transferWritingPage/transferItemList/TransferItemList.tsx
  src/pages/transferWritingPage/transferItemList/transferItem/TransferItem.style.ts
  src/pages/transferWritingPage/transferItemList/transferItem/TransferItem.tsx
  src/routes/router.tsx
  src/styles/globalStyle.ts
  src/styles/theme.ts
  src/types/.gitkeep
  src/types/reservationList.ts
  src/utils/.gitkeep
  src/utils/priceFormat.ts
  tests/unitTestsSrc/transfer-writing.spec.tsx
Labels: FEAT, DESIGN, CHORE, TEST

#57 [#39] 회원가입 페이지 마크업
  src/pages/signUpPage/SignUp.style.ts
  src/pages/signUpPage/SignUp.tsx
  src/pages/signUpPage/index.tsx
  src/routes/router.tsx
Labels: DESIGN

#64 [#58] 로그인 페이지 마크업
  package-lock.json
  package.json
  src/assets/logos/loginlogo.svg
  src/pages/signInPage/SignIn.style.ts
  src/pages/signInPage/SignIn.tsx
  src/pages/signInPage/index.tsx
  src/pages/signUpPage/SignUp.style.ts
  src/routes/router.tsx
  tsconfig.json
  vite.config.ts
Labels: DESIGN

#68 [#63] 헤더/바텀네비 OnOff기능 & 토스트 메시지 컴포넌트
  index.html
  src/components/layout/Layout.style.ts
  src/components/layout/Layout.tsx
  src/components/layout/navBottom/NavBottom.tsx
  src/components/toast/Toast.style.ts
  src/components/toast/Toast.tsx
  src/constants/path.ts
  src/hooks/.gitkeep
  src/pages/homePage/index.tsx
  src/pages/transferWritingPage/TransferWriting.style.ts
  src/pages/transferWritingPage/TransferWriting.tsx
  src/routes/router.tsx
  src/styles/theme.ts
Labels: FEAT, DESIGN

#70 [#66] 비밀번호 재설정 페이지 마크업
  src/constants/path.ts
  src/pages/passwordResetPage/PasswordReset.style.ts
  src/pages/passwordResetPage/PasswordReset.tsx
  src/pages/signInPage/SignIn.tsx
  src/pages/signUpPage/SignUp.style.ts
  src/pages/signUpPage/SignUp.tsx
  src/routes/router.tsx
Labels: DESIGN

#72 [#53] 마이페이지 1차 스프린트 마크업
  src/assets/icons/RightArrow.svg
  src/components/layout/header/HeaderTop.tsx
  src/constants/path.ts
  src/pages/myPage/MyPage.style.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/index.tsx
  src/pages/myPage/info/Info.style.ts
  src/pages/myPage/info/Info.tsx
  src/pages/myPage/manage/Manage.style.ts
  src/pages/myPage/manage/Manage.tsx
  src/pages/myPage/manage/manageAccount/ManageAccount.style.ts
  src/pages/myPage/manage/manageAccount/ManageAccount.tsx
  src/pages/myPage/manage/manageEmail/ManageEmail.style.ts
  src/pages/myPage/manage/manageEmail/ManageEmail.tsx
  src/pages/myPage/manage/manageName/ManageName.style.ts
  src/pages/myPage/manage/manageName/ManageName.tsx
  src/pages/myPage/manage/managePhoneNumber/ManagePhoneNumber.style.ts
  src/pages/myPage/manage/managePhoneNumber/ManagePhoneNumber.tsx
  src/pages/myPage/manage/manageProfile/ManageProfile.style.ts
  src/pages/myPage/manage/manageProfile/ManageProfile.tsx
  src/pages/myPage/setting/Setting.style.ts
  src/pages/myPage/setting/Setting.tsx
  src/routes/router.tsx
  src/styles/theme.ts
Labels: DESIGN

#77 [#59] 회원가입 페이지 react-hook-form 적용 / API 연동 마무리
  package-lock.json
  package.json
  src/pages/signUpPage/SignUp.style.ts
  src/pages/signUpPage/SignUp.tsx
Labels: FEAT

#74 [#62] Carousel 드래그 기능 추가
  src/components/carousel/Carousel.style.ts
  src/components/carousel/Carousel.tsx
  src/hooks/useCarousel.ts
  src/hooks/useCarouselSize.ts
  src/pages/homePage/index.tsx
  src/pages/roomDetailPage/RoomDetail.tsx
Labels: FEAT

#78 [#69] 양도글작성 가격설정 페이지 마크업
  src/apis/fetchTransferItems.ts
  src/components/carousel/Carousel.tsx
  src/components/layout/header/HeaderTop.tsx
  src/components/layout/navBottom/NavBottom.style.ts
  src/constants/path.ts
  src/main.tsx
  src/mocks/data/reservationList.json
  src/pages/signInPage/SignIn.style.ts
  src/pages/signUpPage/SignUp.style.ts
  src/pages/transerWritingPricePage/TransferWritingPrice.style.ts
  src/pages/transerWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPage/TransferWriting.style.ts
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPage/transferItem/TransferItem.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.style.ts
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPricePage/accountSection/AccountSection.style.ts
  src/pages/transferWritingPricePage/accountSection/AccountSection.tsx
  src/pages/transferWritingPricePage/agreementSection/AgreementSection.style.ts
  src/pages/transferWritingPricePage/agreementSection/AgreementSection.tsx
  src/pages/transferWritingPricePage/checkBox/CheckBoxSection.style.ts
  src/pages/transferWritingPricePage/checkBox/CheckBoxSection.tsx
  src/pages/transferWritingPricePage/firstPriceTag/FirstPriceTag.style.ts
  src/pages/transferWritingPricePage/firstPriceTag/FirstPriceTag.tsx
  src/pages/transferWritingPricePage/inputSection/InputSection.style.ts
  src/pages/transferWritingPricePage/inputSection/InputSection.tsx
  src/pages/transferWritingPricePage/paymentSection/PaymentSection.style.ts
  src/pages/transferWritingPricePage/paymentSection/PaymentSection.tsx
  src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.style.ts
  src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.tsx
  src/routes/router.tsx
  src/styles/theme.ts
  src/types/reservationList.ts
Labels: REFACTOR, DESIGN

#83 [#79] 양도글작성 가격페이지 데이터 바인딩 및 예외처리
  package-lock.json
  package.json
  src/App.tsx
  src/apis/fetchTransferItems.ts
  src/apis/fetchUserInfo.ts
  src/components/layout/Layout.tsx
  src/mocks/data/reservationList.json
  src/mocks/data/userInfo.json
  src/mocks/handler.ts
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPage/transferItem/TransferItem.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.style.ts
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPricePage/accountSection/AccountSection.style.ts
  src/pages/transferWritingPricePage/accountSection/AccountSection.tsx
  src/pages/transferWritingPricePage/agreementSection/AgreementSection.tsx
  src/pages/transferWritingPricePage/checkBox/CheckBoxSection.tsx
  src/pages/transferWritingPricePage/firstPriceTag/FirstPriceTag.style.ts
  src/pages/transferWritingPricePage/firstPriceTag/FirstPriceTag.tsx
  src/pages/transferWritingPricePage/inputSection/InputSection.tsx
  src/pages/transferWritingPricePage/paymentSection/PaymentSection.style.ts
  src/pages/transferWritingPricePage/paymentSection/PaymentSection.tsx
  src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.style.ts
  src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.tsx
  src/routes/router.tsx
  src/store/store.ts
  src/types/userInfo.ts
Labels: FEAT, DESIGN

#86 [#65] 로그인 페이지 기능 연결
  src/components/toast/Toast.style.ts
  src/components/toast/Toast.tsx
  src/pages/signInPage/SignIn.tsx
Labels: FEAT

#87 [#80] 비밀번호 찾기 페이지 기능 연결
  src/pages/passwordResetPage/PasswordReset.style.ts
  src/pages/passwordResetPage/PasswordReset.tsx
  src/pages/signUpPage/SignUp.style.ts
Labels: FEAT

#94 [#85] 토스트 전역으로 관리, zustand-persist 사용, 예외 조건 처리
  src/App.tsx
  src/apis/fetchUserInfo.ts
  src/components/toast/Toast.tsx
  src/hooks/usePreventLeave.ts
  src/main.tsx
  src/pages/signInPage/SignIn.tsx
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPricePage/checkBox/CheckBoxSection.style.ts
  src/pages/transferWritingPricePage/checkBox/CheckBoxSection.tsx
  src/pages/transferWritingPricePage/firstPriceTag/FirstPriceTag.tsx
  src/pages/transferWritingPricePage/inputSection/InputSection.tsx
  src/pages/transferWritingPricePage/paymentSection/PaymentSection.tsx
  src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.tsx
  src/store/store.ts
  src/utils/priceFormat.ts
Labels: FEAT

#90 [#76] 야놀자 연동 페이지 마크업
  package-lock.json
  src/assets/icons/ic_percent_hotel.png
  src/assets/icons/ic_x.png
  src/assets/logos/Percent-hotel_logo.png
  src/assets/logos/Percent-hotel_logo_b.png
  src/assets/logos/Yanolja_CI.png
  src/components/checkbox/Checkbox.style.ts
  src/components/checkbox/Checkbox.tsx
  src/components/layout/Layout.tsx
  src/constants/path.ts
  src/pages/connectYanoljaAccountPage/ConnectYanoljaAccount.style.ts
  src/pages/connectYanoljaAccountPage/ConnectYanoljaAccount.tsx
  src/pages/connectYanoljaPage/ConnectYanolja.style.ts
  src/pages/connectYanoljaPage/ConnectYanolja.tsx
  src/pages/connectYanoljaSuccessPage/ConnectYanoljaSuccess.style.ts
  src/pages/connectYanoljaSuccessPage/ConnectYanoljaSuccess.tsx
  src/pages/roomDetailPage/RoomDetail.style.ts
  src/pages/roomDetailPage/components/roomHeader/RoomHeader.style.ts
  src/pages/roomDetailPage/components/roomHeader/RoomHeader.tsx
  src/routes/router.tsx
  src/styles/theme.ts
  src/utils/hexTorgba.ts
Labels: DESIGN

#88 [#73] 프로필 변경 유효성 검사 및 api 연동
  .gitignore
  src/apis/useProfileApi.ts
  src/pages/myPage/manage/manageName/ManageName.style.ts
  src/pages/myPage/manage/manageName/ManageName.tsx
  src/pages/myPage/manage/managePhoneNumber/ManagePhoneNumber.style.ts
  src/pages/myPage/manage/managePhoneNumber/ManagePhoneNumber.tsx
  src/pages/myPage/manage/manageProfile/ManageProfile.tsx
  src/pages/myPage/manage/manageProfile/ManageProfile.type.ts
  src/routes/router.tsx
Labels: FEAT

#98 [#93] 야놀자 연동 페이지 API 연동, 폼 유효성 검사, 유닛테스트
  package-lock.json
  src/components/carousel/Carousel.tsx
  src/components/checkbox/Checkbox.tsx
  src/components/inputField/InputField.style.ts
  src/components/inputField/InputField.tsx
  src/constants/api.ts
  src/hooks/api/mutation/useConnectAccountMutation.ts
  src/hooks/api/mutation/useValidateEmailMutation.ts
  src/hooks/common/useCarousel.ts
  src/hooks/common/useCarouselSize.ts
  src/hooks/common/useIsVisible.ts
  src/hooks/common/usePreventLeave.ts
  src/mocks/broswer.ts
  src/mocks/handler.ts
  src/mocks/handlers/email.ts
  src/mocks/handlers/room.ts
  src/mocks/server.ts
  src/pages/connectYanoljaAccountPage/ConnectYanoljaAccount.style.ts
  src/pages/connectYanoljaAccountPage/ConnectYanoljaAccount.tsx
  src/pages/connectYanoljaPage/IntroPage/IntroPage.style.ts
  src/pages/connectYanoljaPage/IntroPage/IntroPage.tsx
  src/pages/connectYanoljaPage/successPage/SuccessPage.style.ts
  src/pages/connectYanoljaPage/successPage/SuccessPage.tsx
  src/pages/connectYanoljaPage/verificationPage/VerificationPage.style.ts
  src/pages/connectYanoljaPage/verificationPage/VerificationPage.tsx
  src/pages/connectYanoljaPage/verificationPage/components/submitButton/SubmitButton.style.ts
  src/pages/connectYanoljaPage/verificationPage/components/submitButton/SubmitButton.tsx
  src/pages/connectYanoljaPage/verificationPage/components/termsAgreementSection/TermsAgreementSection.style.ts
  src/pages/connectYanoljaPage/verificationPage/components/termsAgreementSection/TermsAgreementSection.tsx
  src/pages/connectYanoljaPage/verificationPage/components/verificationSection/VerificationSection.style.ts
  src/pages/connectYanoljaPage/verificationPage/components/verificationSection/VerificationSection.tsx
  src/pages/myPage/manage/manageName/ManageName.tsx
  src/pages/roomDetailPage/components/roomHeader/RoomHeader.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/routes/router.tsx
  tests/unitTestsSrc/hooks/api/useEmailVerification.spec.tsx
  tests/unitTestsSrc/pages/connectYanoljaPage/VerificationPage.spec.tsx
  tests/unitTestsSrc/setup.ts
  tsconfig.json
Labels: FEAT, REFACTOR, TEST

#102 [#100] 야놀자 연동 페이지 404 에러 시 토스트 메시지 띄우기
  src/apis/axiosInstance.ts
  src/apis/postValidateEmail.ts
  src/apis/postYanoljaAccount.ts
  src/hooks/api/mutation/useConnectAccountMutation.ts
  src/hooks/api/mutation/useValidateEmailMutation.ts
  src/pages/connectYanoljaPage/verificationPage/components/submitButton/SubmitButton.tsx
  src/pages/connectYanoljaPage/verificationPage/components/verificationSection/VerificationSection.tsx
  tsconfig.json
  vite.config.ts
Labels: FIX, REFACTOR

#103 [#93]야놀자 인증 api, 실제 유저정보 api, 판매글 조회 api 연동
  src/apis/fetchTransferItems.ts
  src/apis/fetchTransferItems_realApi.ts
  src/apis/fetchUserInfo.ts
  src/apis/postTransferItems.ts
  src/apis/useProfileApi.ts
  src/assets/icons/frame_TransferDone.svg
  src/constants/path.ts
  src/mocks/handler.ts
  src/pages/connectYanoljaPage/verificationPage/components/verificationSection/VerificationSection.tsx
  src/pages/transferWritingDonePage/TransferWritingSuccess.style.ts
  src/pages/transferWritingDonePage/TransferWritingSuccess.tsx
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPage/transferItem/TransferItem.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPricePage/inputSection/InputSection.tsx
  src/routes/router.tsx
Labels: FIX, FEAT

#104 [#89] 계좌 관리 페이지 마크업
  src/apis/useProfileApi.ts
  src/assets/bankImages/bnk.png
  src/assets/bankImages/daegu.png
  src/assets/bankImages/gwangju.png
  src/assets/bankImages/hana.png
  src/assets/bankImages/ibk.png
  src/assets/bankImages/kBank.png
  src/assets/bankImages/kakaoBank.png
  src/assets/bankImages/kookmin.png
  src/assets/bankImages/nh.png
  src/assets/bankImages/postOffice.png
  src/assets/bankImages/saemaeul.png
  src/assets/bankImages/sc.png
  src/assets/bankImages/sinhan.png
  src/assets/bankImages/sinhyup.png
  src/assets/bankImages/tossBank.png
  src/assets/bankImages/woori.png
  src/components/account/enterAccountInfo/EnterAccountInfo.style.ts
  src/components/account/enterAccountInfo/EnterAccountInfo.tsx
  src/components/account/termsAgreement/PrivacyPolicy.tsx
  src/components/account/termsAgreement/TermsAgreement.style.ts
  src/components/account/termsAgreement/TermsAgreement.tsx
  src/components/layout/header/HeaderTop.tsx
  src/constants/bank.ts
  src/hooks/common/useToastConfig.ts
  src/pages/myPage/manage/accountInfo/AccountInfo.style.ts
  src/pages/myPage/manage/accountInfo/AccountInfo.tsx
  src/pages/myPage/manage/editAccount/EditAccount.style.ts
  src/pages/myPage/manage/editAccount/EditAccount.tsx
  src/pages/myPage/manage/manageAccount/ManageAccount.tsx
  src/pages/myPage/manage/manageEmail/ManageEmail.tsx
  src/pages/myPage/manage/manageName/ManageName.tsx
  src/pages/myPage/manage/managePhoneNumber/ManagePhoneNumber.tsx
  src/pages/myPage/manage/manageProfile/ManageProfile.tsx
  src/pages/myPage/manage/registerAccount/RegisterAccount.style.ts
  src/pages/myPage/manage/registerAccount/RegisterAccount.tsx
  src/types/account.ts
Labels: FEAT, DESIGN

#105 [#99] (로컬) 에러바운더리 구현, axios Instance & interceptor 구현
  package-lock.json
  package.json
  src/apis/axiosInstance.ts
  src/apis/fetchNewToken.ts
  src/components/error/Error.tsx
  src/components/errorBoundary/LocalErrorBoundary.tsx
  src/constants/api.ts
  src/constants/regex.ts
  src/hooks/api/mutation/useConnectAccountMutation.ts
  src/hooks/api/mutation/useValidateEmailMutation.ts
  src/mocks/handler.ts
  src/mocks/handlers/email.ts
  src/pages/connectYanoljaPage/verificationPage/components/verificationSection/VerificationSection.tsx
  src/pages/passwordResetPage/PasswordReset.tsx
  src/pages/signUpPage/SignUp.tsx
  src/routes/router.tsx
  src/types/newToken.ts
Labels: FIX, REFACTOR, CHORE

#113 [#95] 판매글작성 계좌연결 플로우 구현, 비로그인/비인증 시 양도글작성 fallback 화면 표출
  src/apis/axiosInstance.ts
  src/apis/fetchTransferItems.ts
  src/apis/fetchUserInfo.ts
  src/apis/postAccount.ts
  src/apis/postTransferItems.ts
  src/components/carousel/Carousel.style.ts
  src/components/carousel/Carousel.tsx
  src/components/layout/Layout.tsx
  src/components/layout/transferWritingPriceHeader/TransferPricingHeaderTop.style.ts
  src/components/layout/transferWritingPriceHeader/TransferPricingHeaderTop.tsx
  src/constants/api.ts
  src/mocks/handler.ts
  src/pages/homePage/Home.style.ts
  src/pages/homePage/Home.tsx
  src/pages/homePage/index.tsx
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.style.ts
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPricePage/accountSection/AccountSection.tsx
  src/pages/transferWritingPricePage/enterAccountInfo/EnterAccountInfo.style.ts
  src/pages/transferWritingPricePage/enterAccountInfo/EnterAccountInfo.tsx
  src/pages/transferWritingSuccessPage/TransferWritingSuccess.style.ts
  src/pages/transferWritingSuccessPage/TransferWritingSuccess.tsx
  src/routes/router.tsx
  src/store/store.ts
  src/types/account.ts
  src/types/nullable.ts
  src/types/postTransferItem.ts
  src/types/userInfo.ts
Labels: FEAT, DESIGN

#118 [#117] axios 공통 instance 사용 및 계좌 및 프로필 페이지 return 구조 변경
  src/apis/patchAccount.ts
  src/apis/useProfileApi.ts
  src/pages/myPage/manage/manageAccount/ManageAccount.tsx
  src/pages/myPage/manage/manageProfile/ManageProfile.tsx
Labels: FIX, REFACTOR

#121 [#120] interceptor 무한루프 에러 해결, 토큰 재발급 반환값 수정
  src/apis/fetchNewToken.ts
  src/constants/api.ts
  src/types/responseType.ts
Labels: FIX

#112 [#109] 계좌등록 api 연동
  src/App.tsx
  src/apis/patchAccount.ts
  src/apis/useProfileApi.ts
  src/components/account/enterAccountInfo/EnterAccountInfo.style.ts
  src/components/account/enterAccountInfo/EnterAccountInfo.tsx
  src/components/account/termsAgreement/TermsAgreement.style.ts
  src/components/account/termsAgreement/TermsAgreement.tsx
  src/components/layout/Layout.tsx
  src/components/layout/header/HeaderTop.tsx
  src/constants/path.ts
  src/pages/myPage/manage/Manage.tsx
  src/pages/myPage/manage/accountInfo/AccountInfo.style.ts
  src/pages/myPage/manage/accountInfo/AccountInfo.tsx
  src/pages/myPage/manage/editAccount/EditAccount.tsx
  src/pages/myPage/manage/manageAccount/ManageAccount.tsx
  src/pages/myPage/manage/manageProfile/ManageProfile.tsx
  src/pages/myPage/manage/manageProfile/ManageProfile.type.ts
  src/pages/myPage/manage/registerAccount/RegisterAccount.tsx
  src/routes/router.tsx
  src/types/account.ts
Labels: FIX, FEAT

#126 [#110] 결제 페이지 마크업
  src/apis/fetchPayment.ts
  src/apis/getRoom.ts
  src/assets/icons/ic_kakao_pay.png
  src/constants/path.ts
  src/hooks/api/query/usePaymentQuery.ts
  src/mocks/data/dummyPaymentInfo.json
  src/mocks/handler.ts
  src/mocks/handlers/payment.ts
  src/mocks/handlers/room.ts
  src/pages/paymentPage/Payment.style.ts
  src/pages/paymentPage/Payment.tsx
  src/pages/paymentPage/components/paymentButton/PaymentButton.style.ts
  src/pages/paymentPage/components/paymentButton/PaymentButton.tsx
  src/pages/paymentPage/components/paymentInfoSection/PaymentInfoSection.style.ts
  src/pages/paymentPage/components/paymentInfoSection/PaymentInfoSection.tsx
  src/pages/paymentPage/components/paymentMethodSection/PaymentMethodSection.style.ts
  src/pages/paymentPage/components/paymentMethodSection/PaymentMethodSection.tsx
  src/pages/paymentPage/components/termsAgreementSection/TermsAgreementSection.style.ts
  src/pages/paymentPage/components/termsAgreementSection/TermsAgreementSection.tsx
  src/pages/paymentPage/components/userInfoSection/UserInfoSection.style.ts
  src/pages/paymentPage/components/userInfoSection/UserInfoSection.tsx
  src/pages/roomDetailPage/RoomDetail.style.ts
  src/pages/roomDetailPage/components/roomInfo/RoomInfo.tsx
  src/pages/transferPurchasePage/components/puchaseItem/PuchaseItem.tsx
  src/routes/router.tsx
  src/types/payment.ts
  src/utils/dateFormatter.ts
Labels: DESIGN

#130 [#128] 결제 페이지 결제요청 api 연동
  package.json
  public/mockServiceWorker.js
  src/apis/axiosInstance.ts
  src/apis/fetchLogin.ts
  src/apis/fetchNewToken.ts
  src/apis/fetchPayment.ts
  src/apis/fetchRoom.ts
  src/apis/fetchYanoljaAccount.ts
  src/apis/postValidateEmail.ts
  src/apis/postYanoljaAccount.ts
  src/components/caption/Caption.tsx
  src/components/caption/Cation.style.ts
  src/components/checkbox/Checkbox.style.ts
  src/constants/api.ts
  src/constants/regex.ts
  src/hooks/api/mutation/useConnectAccountMutation.ts
  src/hooks/api/mutation/usePaymentMutation.ts
  src/hooks/api/mutation/usePaymentRequestMutation.ts
  src/hooks/api/mutation/useValidateEmailMutation.ts
  src/hooks/api/query/usePaymentQuery.ts
  src/hooks/common/useLoadUserInfo.ts
  src/pages/connectYanoljaPage/verificationPage/components/verificationSection/VerificationSection.tsx
  src/pages/paymentPage/Payment.style.ts
  src/pages/paymentPage/Payment.tsx
  src/pages/paymentPage/components/paymentButton/PaymentButton.tsx
  src/pages/paymentPage/components/paymentMethodSection/PaymentMethodSection.style.ts
  src/pages/paymentPage/components/paymentMethodSection/PaymentMethodSection.tsx
  src/pages/paymentPage/components/termsAgreementSection/TermsAgreementSection.tsx
  src/pages/paymentPage/components/userInfoSection/UserInfoSection.style.ts
  src/pages/paymentPage/components/userInfoSection/UserInfoSection.tsx
  src/pages/roomDetailPage/RoomDetail.tsx
  src/pages/signInPage/SignIn.tsx
  src/routes/router.tsx
  src/store/store.ts
  src/types/login.ts
  src/types/newToken.ts
  src/types/payment.ts
  tests/unitTestsSrc/hooks/api/useEmailVerification.spec.tsx
Labels: FEAT

#134 [#107] 메인페이지 마크업, 알림페이지 마크업
  package-lock.json
  package.json
  public/firebase-messaging-sw.js
  src/App.tsx
  src/apis/axiosInstance.ts
  src/apis/fetchLogin.ts
  src/apis/fetchMainItems.ts
  src/apis/postTransferItems.ts
  src/assets/logos/main_logo.svg
  src/components/itemCarousel/ItemCarousel.style.ts
  src/components/itemCarousel/ItemCarousel.tsx
  src/components/itemCarousel/itemCarouselUnit/ItemCarouselUnit.style.ts
  src/components/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
  src/components/layout/Layout.tsx
  src/components/layout/header/HeaderTop.tsx
  src/constants/api.ts
  src/constants/locale.ts
  src/constants/path.ts
  src/firebase-messaging-sw.js
  src/firebase.ts
  src/hooks/common/useCarousel.ts
  src/pages/homePage/Home.style.ts
  src/pages/homePage/Home.tsx
  src/pages/homePage/mainHeader/MainHeader.style.ts
  src/pages/homePage/mainHeader/MainHeader.tsx
  src/pages/homePage/navToSearchSection/NavToSearchSection.style.ts
  src/pages/homePage/navToSearchSection/NavToSearchSection.tsx
  src/pages/homePage/titleSection/TitleSection.style.ts
  src/pages/homePage/titleSection/TitleSection.tsx
  src/pages/homePage/weekendCarousel/WeekendCarousel.style.ts
  src/pages/homePage/weekendCarousel/WeekendCarousel.tsx
  src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.style.ts
  src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.tsx
  src/pages/noticePage/NoticePage.style.ts
  src/pages/noticePage/NoticePage.tsx
  src/pages/signInPage/SignIn.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingSuccessPage/TransferWritingSuccess.style.ts
  src/routes/router.tsx
  src/types/postTransferItem.ts
  src/types/saleSection.ts
  src/utils/maximumSaleInLocale.ts
Labels: DESIGN

#145 [#143] 마이페이지 내 야놀자 연동 버튼 활성화
  src/pages/myPage/MyPage.style.ts
  src/pages/myPage/MyPage.tsx
Labels: FEAT

#142 [#141] 로그인 후 이전 페이지로 리다이렉션 로직 추가
  src/apis/axiosInstance.ts
  src/pages/myPage/MyPage.style.ts
  src/pages/myPage/MyPage.tsx
  src/pages/signInPage/SignIn.tsx
Labels: REFACTOR

#140 [#138] 로그아웃 구현
  src/apis/axiosInstance.ts
  src/apis/logout.ts
  src/components/account/enterAccountInfo/EnterAccountInfo.style.ts
  src/pages/myPage/MyPage.style.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/info/Info.style.ts
  src/pages/myPage/info/Info.tsx
  src/pages/myPage/manage/Manage.tsx
  src/pages/myPage/manage/editAccount/EditAccount.tsx
  src/pages/signInPage/SignIn.tsx
Labels: FEAT

#137 [#136] 야놀자 연동이 되지 않은 사용자는 계좌 설정 탭이 보이지 않도록 수정
  package-lock.json
  public/mockServiceWorker.js
  src/apis/axiosInstance.ts
  src/apis/logout.ts
  src/components/account/enterAccountInfo/EnterAccountInfo.style.ts
  src/hooks/useOnClickOutside.ts
  src/pages/myPage/MyPage.style.ts
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/info/Info.style.ts
  src/pages/myPage/info/Info.tsx
  src/pages/myPage/manage/Manage.style.ts
  src/pages/myPage/manage/Manage.tsx
  src/pages/myPage/manage/editAccount/EditAccount.tsx
  src/pages/myPage/manage/manageAccount/ManageAccount.tsx
  src/pages/signInPage/SignIn.tsx
Labels: FIX

#160 [#157] 로그인 페이지 로고 링크 추가
  src/pages/signInPage/SignIn.tsx
Labels: FEAT

#151 [#148] 알람내역 api 연동, 알람 여부 api 연동
  src/apis/fetchAlarm.ts
  src/apis/fetchHasAlarm.ts
  src/components/layout/header/HeaderTop.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/mocks/handler.ts
  src/pages/alarmPage/AlarmPage.style.ts
  src/pages/alarmPage/AlarmPage.tsx
  src/pages/homePage/Home.tsx
  src/pages/homePage/itemCarousel/ItemCarousel.style.ts
  src/pages/homePage/itemCarousel/ItemCarousel.tsx
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.style.ts
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
  src/pages/homePage/mainHeader/MainHeader.tsx
  src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.tsx
  src/pages/noticePage/NoticePage.tsx
  src/routes/router.tsx
  src/types/alarm.ts
Labels: FEAT

#161 [#153] 메인페이지 텍스트 애니메이션
  src/apis/fetchMainItems.ts
  src/hooks/common/useAnimateCarousel.ts
  src/pages/homePage/Home.style.ts
  src/pages/homePage/Home.tsx
  src/pages/homePage/itemCarousel/ItemCarousel.tsx
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.style.ts
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
  src/pages/homePage/percentAnimator/PercentAnimator.style.ts
  src/pages/homePage/percentAnimator/PercentAnimator.tsx
  src/pages/homePage/textAnimator/TextAnimator.style.ts
  src/pages/homePage/textAnimator/TextAnimator.tsx
  src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.tsx
  src/types/saleSection.ts
Labels: DESIGN

#171 [#167] 홈 - 검색필터 => 일정선택 페이지로 라우팅 변경
  src/pages/homePage/navToSearchSection/NavToSearchSection.tsx
Labels: FIX

#174 [#166]양도글 작성 QA 진행
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPricePage/inputSection/InputSection.tsx
  src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.tsx
Labels: FIX

#176 [#175] fix: axios instance 사용 안함
  src/apis/fetchRoom.ts
Labels: FIX

#178 [#177] 메인페이지에 0 뜨는 버그 수정
  src/apis/fetchMainItems.ts
  src/main.tsx
  src/pages/homePage/Home.tsx
  src/pages/homePage/percentAnimator/PercentAnimator.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
Labels: FIX, CHORE

#180 [#179] 캐로셀 할인률 반대로 나오는 이슈 수정
  src/pages/homePage/Home.tsx
  src/pages/homePage/itemCarousel/ItemCarousel.tsx
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
  src/pages/homePage/percentAnimator/PercentAnimator.tsx
Labels: FIX

#186 [#185] 2차 가격을 설정해야만 진행되는 버그 수정
  index.html
  src/assets/logos/favicon.svg
  src/components/layout/Layout.tsx
  src/pages/homePage/percentAnimator/PercentAnimator.style.ts
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPricePage/enterAccountInfo/EnterAccountInfo.tsx
  src/pages/transferWritingSuccessPage/TransferWritingSuccess.tsx
  src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.style.ts
  src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx
Labels: FIX

#183 [#116] 마이페이지 내 판매내역 및 판매내역 상세 페이지 마크업 및 연동 일부 완료
  src/apis/cancelSale.ts
  src/apis/fetchSaleDetail.ts
  src/apis/fetchSaleList.ts
  src/components/caption/Cation.style.ts
  src/components/layout/header/HeaderTop.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/constants/sale.ts
  src/constants/time.ts
  src/hooks/api/query/useSaleDetailQuery.ts
  src/mocks/data/dummySaleDetail.json
  src/mocks/data/dummySaleList.json
  src/mocks/handler.ts
  src/pages/saleDetailPage/SaleDetail.style.ts
  src/pages/saleDetailPage/SaleDetail.tsx
  src/pages/saleDetailPage/saleButton/SaleButton.style.ts
  src/pages/saleDetailPage/saleButton/SaleButton.tsx
  src/pages/saleDetailPage/saleInfo/SaleInfo.tsx
  src/pages/transferSalePage/TransferSale.style.ts
  src/pages/transferSalePage/TransferSale.tsx
  src/pages/transferSalePage/components/saleItem/SaleItem.style.ts
  src/pages/transferSalePage/components/saleItem/SaleItem.tsx
  src/pages/transferSalePage/components/saleNav/SaleNav.style.ts
  src/pages/transferSalePage/components/saleNav/SaleNav.tsx
  src/pages/transferSalePage/index.tsx
  src/routes/router.tsx
  src/types/saleDetail.ts
  src/types/saleList.ts
  src/utils/calculator.ts
  src/utils/dateFormatter.ts
Labels: FEAT, DESIGN

#162 [#155] 결제 페이지 조회 전 재고 확인
  src/apis/fetchPayment.ts
  src/apis/fetchRoom.ts
  src/components/layout/Layout.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/api/mutation/useConnectAccountMutation.tsx
  src/hooks/api/mutation/usePaymentMutation.ts
  src/hooks/api/useStockQuery.ts
  src/main.tsx
  src/mocks/data/dummyRoomDetail.json
  src/mocks/data/dummyStock.json
  src/mocks/handler.ts
  src/mocks/handlers/email.ts
  src/mocks/handlers/room.ts
  src/mocks/handlers/yanoljaAccount.ts
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
  src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.tsx
  src/pages/roomDetailPage/RoomDetail.tsx
  src/pages/roomDetailPage/components/roomNavBar/RoomNavBar.tsx
  src/pages/searchPage/components/searchItem/SearchItem.tsx
  src/routes/router.tsx
  src/types/payment.ts
Labels: FEAT

#190 [#185] 바텀시트 플로우, 메인페이지 qa 대응, 양도글 작성 qa 대응
  src/apis/fetchMainItems.ts
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.style.ts
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
  src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.style.ts
  src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.tsx
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPage/transferItem/TransferItem.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPricePage/enterAccountInfo/EnterAccountInfo.tsx
  src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.tsx
  src/pages/transferWritingSuccessPage/TransferWritingSuccess.tsx
  src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.style.ts
  src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx
Labels: FIX, FEAT

#194 [#191] 반올림 처리 및 주석 추가
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
Labels: FIX

#197 [#195] 글로벌 서스펜스 추가 및 모든 서스펜스에 로딩컴포넌트 추가
  src/routes/router.tsx
Labels: FEAT

#165 [#124] 회원가입 페이지 리팩토링
  src/pages/signUpPage/SignUp.style.ts
  src/pages/signUpPage/SignUp.tsx
  src/pages/signUpPage/components/fieldValues/FieldValues.tsx
  src/pages/signUpPage/components/signUpSubmitBtn/SignUpSubmitBtn.tsx
Labels: REFACTOR

#172 [#169] 비밀번호 찾기 페이지 리팩토링
  src/pages/passwordResetPage/PasswordReset.tsx
  src/pages/passwordResetPage/components/fieldValues/FieldValues.tsx
  src/pages/passwordResetPage/components/passwordResetSubmitBtn.tsx/PasswordResetSubmitBtn.tsx
Labels: REFACTOR

#202 [#201] qa대응 - 계좌번호 등록 사파리에서 안 되는 이슈
  src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx
Labels: FIX

#204 [#201] 정렬 수정 및 모바일 캐로셀 대응
  src/pages/homePage/Home.tsx
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
  src/pages/homePage/percentAnimator/PercentAnimator.tsx
Labels: FIX

#203 [#188] 입력필드 수정 시 체크박스 해제되도록 수정
  src/pages/paymentPage/components/userInfoSection/UserInfoSection.tsx
  src/pages/roomDetailPage/RoomDetail.style.ts
Labels: FIX, REFACTOR

#208 [#207]캐로셀 버튼컨테이너 클릭 전파 가능하게 수정
  src/pages/homePage/itemCarousel/ItemCarousel.style.ts
  src/pages/homePage/weekendCarousel/WeekendCarousel.style.ts
Labels: FIX

#209 [#206] 페이지 마다 scroll to top 적용
  src/App.tsx
  src/components/scrollToTop/ScrollToTop.tsx
Labels: FEAT

#220 [#150] pwa 세팅
  index.html
  package-lock.json
  package.json
  public/apple-touch-icon-180x180.png
  public/favicon.ico
  public/icon-192-maskable.png
  public/icon-192.png
  public/icon-512-maskable.png
  public/icon-512.png
  public/logo.svg
  public/maskable-icon-512x512.png
  public/vite.svg
  tsconfig.json
  vite.config.ts
Labels: FEAT, CHORE

#222 구매내역 판매내역 NoResult처리
  src/apis/fetchSaleDetail.ts
  src/apis/fetchSaleList.ts
  src/components/layout/header/HeaderTop.tsx
  src/constants/api.ts
  src/constants/path.ts
  src/hooks/api/query/useSaleDetailQuery.ts
  src/pages/myPage/MyPage.tsx
  src/pages/paymentSuccessPage/components/PaymentSuccessButton/PaymentSuccessButton.tsx
  src/pages/saleDetailPage/SaleDetail.tsx
  src/pages/searchPage/Search.tsx
  src/pages/transferPurchasePage/TransferPurchase.style.ts
  src/pages/transferPurchasePage/TransferPurchase.tsx
  src/pages/transferPurchasePage/components/puchaseItem/PuchaseItem.tsx
  src/pages/transferSalePage/TransferSale.style.ts
  src/pages/transferSalePage/TransferSale.tsx
  src/pages/transferWritingSuccessPage/TransferWritingSuccess.tsx
  src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx
  src/routes/router.tsx
Labels: FEAT

#224 [#221] PWA 등록 안됨 이슈 해결
  index.html
  manifest.json
  package-lock.json
  package.json
  public/logo.svg
  public/offline.html
  public/pwabuilder-sw.js
  tsconfig.json
  vite.config.ts
Labels: FIX, CHORE

#226 [#225] PWA 아이콘 변경, 캐시 사용
  manifest.json
  offline.html
  public/pwabuilder-sw.js
Labels: FIX, CHORE

#230 [#227] 캐로셀 버튼 복구, 신규알람여부api axios로 변경 및 예외처리, 알람 없을 때 화면, 판매글 없을 때 화면, 판매글 작성 시 남은 시간 잘 안나오는 케이스 수정, 파비콘 검은색으로 수정(pr 작성 중)
  src/apis/fetchHasAlarm.ts
  src/assets/logos/favicon.svg
  src/pages/alarmPage/AlarmPage.tsx
  src/pages/homePage/itemCarousel/ItemCarousel.style.ts
  src/pages/homePage/itemCarousel/ItemCarousel.tsx
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
  src/pages/homePage/weekendCarousel/WeekendCarousel.style.ts
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.tsx
  src/utils/checkToken.ts
Labels: FIX, DESIGN

#231 판매 상세페이지 api연동 로직 수정 & 검색바 문구 수정 &구매상세 이동 루트 수정& 달력 모달 하위버튼영역 absolute 에서 fixed로 수정
  dev-dist/registerSW.js
  dev-dist/sw.js
  dev-dist/workbox-b5f7729d.js
  src/apis/fetchSaleDetail.ts
  src/constants/api.ts
  src/hooks/api/query/useSaleDetailQuery.ts
  src/pages/homePage/mainHeader/MainHeader.style.ts
  src/pages/paymentSuccessPage/components/PaymentSuccessButton/PaymentSuccessButton.tsx
  src/pages/saleDetailPage/SaleDetail.tsx
  src/pages/searchFilterPage/components/calendarModal/CalendarModal.style.ts
  src/pages/searchFilterPage/components/calendarModal/CalendarModal.tsx
  src/pages/searchPage/components/searchBar/SearchBar.tsx
  src/pages/transferSalePage/TransferSale.tsx
  src/pages/transferSalePage/components/saleItem/SaleItem.tsx
  src/types/saleDetail.ts
  src/types/saleList.ts
Labels: FIX, FEAT, REFACTOR

#233 [#232] 타입에러 수정 후 재배포
  src/pages/homePage/mainHeader/MainHeader.tsx
Labels: FIX

#235 [#234] pwa start_url 변경
  dev-dist/registerSW.js
  dev-dist/sw.js
  dev-dist/workbox-b5f7729d.js
  index.html
  manifest.json
Labels: FIX, CHORE

#219 [#205] 모바일에서 터치 안되는 이슈 해결, 이벤트 버블링 막기
  src/hooks/common/useAnimateCarousel.ts
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
Labels: FIX

#239 [#236] 토큰 임시로 렌더링 되도록
  src/pages/signInPage/SignIn.tsx
Labels: FIX

#240 [#236] fcm 토큰 발급 후 백엔드에 전달
  src/pages/signInPage/SignIn.tsx
Labels: FIX, FEAT

#242 검색 검색필터 판매 상세 페이지 container padding top 수정 & 알람 아이콘 변경 및 navigate 추가 & 검색페이지 hover이벤트 추가 & 달력 모달 css 수정
  src/components/layout/Layout.style.ts
  src/components/layout/header/HeaderTop.tsx
  src/pages/homePage/mainHeader/MainHeader.style.ts
  src/pages/myPage/components/myPageNav/MyPageNav.style.ts
  src/pages/saleDetailPage/SaleDetail.style.ts
  src/pages/searchFilterPage/SearchFilter.style.ts
  src/pages/searchFilterPage/SearchFilter.tsx
  src/pages/searchFilterPage/components/calendarModal/CalendarModal.style.ts
  src/pages/searchPage/Search.style.ts
  src/pages/searchPage/components/searchBar/SearchBar.style.ts
  src/pages/searchPage/components/searchModalButton/SearchModalButton.style.ts
  src/pages/searchPage/components/searchNav/SearchNav.style.ts
Labels: FIX, DESIGN

#251 [#249] ghAction 환경변수 재설정
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  src/App.tsx
Labels: CHORE

#258 [#257] 알림 허용 안 할 시 fcm토큰 발급 요청 안되도록 수정
  src/apis/fetchLogin.ts
  src/firebase.ts
  src/pages/signInPage/SignIn.tsx
  src/utils/getNotificationPermission.ts
Labels: FIX

#265 [#246] 바텀네비 툴팁 추가
  src/components/layout/navBottom/NavBottom.tsx
  src/components/layout/navBottom/toolTip/ToolTip.style.ts
  src/components/layout/navBottom/toolTip/ToolTip.tsx
Labels: FEAT, DESIGN, CHORE

#262 [#181] 캐로셀 인디케이터 클릭 시 해당 섹션으로 이동 기능 추가, 주말특가 캐로셀 화살표 다음 버튼 눌렀을 때 넘어가는 범위 일정치 않은 버그 수정
  src/pages/homePage/Home.style.ts
  src/pages/homePage/Home.tsx
  src/pages/homePage/itemCarousel/ItemCarousel.tsx
  src/pages/homePage/sequenceSection/SequenceSection.style.ts
  src/pages/homePage/sequenceSection/SequenceSection.tsx
  src/pages/homePage/weekendCarousel/WeekendCarousel.tsx
  src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.style.ts
Labels: FEAT

#267 [#173] 계좌입력 안 해도 진행되는 버그 수정, 계좌 연결 플로우 타다가 돌아와도 체크박스 살아있게 수정, 계좌 연결 플로우 타다가 돌아와도 체크박스 살아있게 수정, 메인 검색바 문구 변경, postValidateEmail을 instance가 아닌 axios로 변경
  src/apis/fetchLogin.ts
  src/pages/homePage/navToSearchSection/NavToSearchSection.tsx
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingPricePage/agreementSection/AgreementSection.tsx
Labels: FIX

#268 [#265] 비동기에러 에러바운더리로 던지기
  src/firebase-messaging-sw.js
  src/pages/roomDetailPage/components/roomNavBar/RoomNavBar.tsx
  src/store/authStore.ts
Labels: FIX

#269 [#188] 결제 페이지 QA 및 에러 해결
  src/components/modal/Modal.style.ts
  src/hooks/api/usePaymentQuery.ts
  src/pages/paymentPage/Payment.tsx
  src/pages/paymentPage/components/userInfoSection/UserInfoSection.tsx
Labels: FIX

#276 [#263] 첫 계좌 등록 시 새로운 계좌로 등록할 때 useNavigate의 state를 활용. (아이폰 사파리에서 안 되는 버그 해결)
  src/apis/postAccount.ts
  src/pages/transferWritingPricePage/TransferWritingPrice.tsx
  src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx
  src/store/store.ts
Labels: FIX, FEAT

#274 [#271] 모바일 사파리일 경우 예외처리
  src/apis/logout.ts
  src/firebase.ts
  src/pages/alarmPage/AlarmPage.tsx
  src/pages/signInPage/SignIn.tsx
  src/utils/getNotificationPermission.ts
  src/utils/isMobileSafari.ts
Labels: FIX, FEAT

#279 [#270] PWA A2HS 기능 구현
  index.html
  src/App.tsx
  src/assets/icons/ic_percent_hotel-app.png
  src/components/A2HS/A2HS.style.ts
  src/components/A2HS/A2HS.tsx
  src/components/account/enterAccountInfo/EnterAccountInfo.style.ts
  src/components/isLogin/IsLogin.tsx
  src/components/layout/Layout.tsx
  src/components/layout/header/HeaderTop.style.ts
  src/components/layout/navBottom/NavBottom.style.ts
  src/components/layout/navBottom/toolTip/ToolTip.style.ts
  src/firebase.ts
  src/hooks/common/useA2HS.ts
  src/hooks/common/useUnmountAnimation.ts
  src/pages/myPage/components/myPageNav/MyPageNav.style.ts
  src/pages/myPage/info/Info.style.ts
  src/pages/purchaseDetailPage/PurchaseDetail.style.ts
  src/pages/roomDetailPage/components/roomNavBar/RoomNavBar.style.ts
  src/pages/roomDetailPage/components/roomNavBar/RoomNavBar.tsx
  src/pages/saleDetailPage/saleButton/SaleButton.style.ts
  src/pages/searchPage/Search.style.ts
  src/pages/searchPage/components/filterModal/FilterModal.style.ts
  src/pages/searchPage/components/searchBar/SearchBar.style.ts
  src/pages/searchPage/components/searchNav/SearchNav.style.ts
  src/pages/transferWritingPricePage/enterAccountInfo/EnterAccountInfo.style.ts
  src/pages/transferWritingPricePage/transferWritingPriceHeader/TransferPricingHeaderTop.style.ts
  src/utils/a2hs.ts
Labels: FEAT, DESIGN

#284 구매 판매 리스트 구매 판매 상세 페이지 api 및 css 수정 & filterbutton 수정 &img lazyloading 처리
  src/apis/fetchPurchaseList.ts
  src/pages/purchaseDetailPage/PurchaseDetail.style.ts
  src/pages/saleDetailPage/SaleDetail.style.ts
  src/pages/saleDetailPage/SaleDetail.tsx
  src/pages/searchPage/Search.tsx
  src/pages/searchPage/components/searchItem/SearchItem.tsx
  src/pages/searchPage/components/searchModalButton/SearchModalButton.style.ts
  src/pages/transferPurchasePage/TransferPurchase.tsx
  src/pages/transferPurchasePage/components/puchaseItem/PuchaseItem.tsx
  src/pages/transferSalePage/TransferSale.tsx
  src/pages/transferSalePage/components/saleItem/SaleItem.tsx
  src/pages/transferWritingPage/transferItem/TransferItem.tsx
Labels: FIX

#290 [#289] 토큰 저장 로직 제거
  src/apis/logout.ts
  src/pages/signInPage/SignIn.tsx
Labels: FIX, FEAT

#292 [#288] 반응형 대응 ui 수정
  index.html
  src/apis/fetchUserInfo.ts
  src/apis/patchAccount.ts
  src/apis/useProfileApi.ts
  src/components/A2HS/A2HS.style.ts
  src/components/A2HS/A2HS.tsx
  src/components/account/enterAccountInfo/EnterAccountInfo.tsx
  src/components/layout/Layout.tsx
  src/components/layout/navBottom/NavBottom.style.ts
  src/components/layout/navBottom/NavBottom.tsx
  src/constants/api.ts
  src/constants/regex.ts
  src/hooks/api/useUserInfoQuery.ts
  src/hooks/common/useLoadUserInfo.ts
  src/hooks/common/useTooltip.ts
  src/pages/connectYanoljaPage/IntroPage/IntroPage.style.ts
  src/pages/connectYanoljaPage/IntroPage/IntroPage.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/info/Info.tsx
  src/pages/myPage/manage/Manage.tsx
  src/pages/myPage/manage/accountInfo/AccountInfo.style.ts
  src/pages/myPage/manage/accountInfo/AccountInfo.tsx
  src/pages/myPage/manage/manageAccount/ManageAccount.tsx
  src/pages/myPage/manage/manageName/ManageName.tsx
  src/pages/myPage/manage/managePhoneNumber/ManagePhoneNumber.tsx
  src/pages/myPage/manage/manageProfile/ManageProfile.style.ts
  src/pages/myPage/manage/manageProfile/ManageProfile.tsx
  src/pages/myPage/manage/manageProfile/ManageProfile.type.ts
  src/pages/myPage/manage/registerAccount/RegisterAccount.tsx
  src/pages/searchPage/Search.tsx
  src/pages/searchPage/components/filterModal/FilterModal.style.ts
  src/pages/searchPage/components/filterModal/FilterModal.tsx
  src/pages/searchPage/components/searchNav/SearchNav.tsx
  src/pages/transferWritingPage/TransferWriting.style.ts
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPricePage/accountSection/AccountSection.tsx
  src/routes/router.tsx
  src/store/store.ts
  src/styles/globalStyle.ts
  src/types/account.ts
  src/types/login.ts
  src/types/profile.ts
  src/types/userInfo.ts
  src/utils/a2hs.ts
  src/utils/tooltip.ts
Labels: REFACTOR, DESIGN

#294 [#272] 리액트 헬멧 SEO 최적화 시도
  package-lock.json
  package.json
  src/components/Helmet/Helmet.tsx
  src/main.tsx
  src/pages/homePage/Home.style.ts
  src/pages/roomDetailPage/RoomDetail.tsx
  src/pages/saleDetailPage/SaleDetail.tsx
  src/routes/router.tsx
Labels: FEAT

#296 [#295] data-react-helmet=true 설정
  src/components/Helmet/Helmet.tsx
Labels: FIX

#297 [#96] Redirection 컴포넌트 구현
  package-lock.json
  package.json
  src/components/redirect/Redirect.tsx
  src/hooks/api/useUserInfoQuery.ts
  src/main.tsx
  src/pages/connectYanoljaPage/verificationPage/VerificationPage.tsx
  src/pages/purchaseDetailPage/PurchaseDetail.style.ts
  src/pages/purchaseDetailPage/PurchaseDetail.tsx
  src/pages/saleDetailPage/SaleDetail.tsx
  src/pages/saleDetailPage/saleInfo/SaleInfo.tsx
  src/routes/router.tsx
Labels: FIX, FEAT

#301 [#299] code splitting 적용, 사이트맵 제작, robots.tsx 등록
  index.html
  package-lock.json
  package.json
  public/robots.txt
  public/sitemap.xml
  src/App.tsx
  src/components/Helmet/Helmet.tsx
  src/main.tsx
  src/pages/signInPage/SignIn.tsx
  src/routes/lazy.ts
  src/routes/router.tsx
Labels: FEAT, REFACTOR

#309 검색페이지 탑버튼 누락 문제해결 & layout 컴포넌트 css 수정 & 달력 컴포넌트 css 수정 & 판매리스트 필터링오류 문제 해결
  package-lock.json
  src/apis/fetchSaleList.ts
  src/components/layout/Layout.style.ts
  src/components/layout/navBottom/NavBottom.style.ts
  src/pages/roomDetailPage/components/roomHeader/RoomHeader.tsx
  src/pages/searchFilterPage/components/calendarModal/CalendarModal.style.ts
  src/pages/searchFilterPage/components/regionModal/RegionModal.tsx
  src/pages/searchPage/Search.style.ts
  src/pages/searchPage/Search.tsx
  src/pages/transferSalePage/components/saleItem/SaleItem.tsx
  src/styles/globalStyle.ts
Labels: FIX

#310 [#308] 백그라운드 메시지 수신 받도록 수정, 점진적 이미지 로딩 적용
  public/firebase-messaging-sw.js
  src/apis/cancelSale.ts
  src/apis/fetchNewToken.ts
  src/apis/fetchRoom.ts
  src/apis/fetchSaleDetail.ts
  src/apis/fetchSaleList.ts
  src/components/A2HS/A2HS.style.ts
  src/components/A2HS/A2HS.tsx
  src/components/carousel/Carousel.tsx
  src/components/deferredComponent/DeferredComponent.tsx
  src/components/deferredComponent/LoadingFallback.tsx
  src/components/isLogin/IsLogin.tsx
  src/components/progressiveImg/ProgressiveImg.tsx
  src/components/progressiveImg/style.ts
  src/constants/api.ts
  src/constants/queryKey.ts
  src/hooks/api/useConnectAccountMutation.tsx
  src/hooks/api/usePaymentQuery.ts
  src/hooks/api/useRoomQuery.ts
  src/hooks/api/useSaleDetailQuery.ts
  src/hooks/api/useSaleQuery.ts
  src/hooks/api/useUserInfoQuery.ts
  src/hooks/common/useLoadUserInfo.ts
  src/pages/alarmPage/AlarmPage.tsx
  src/pages/connectYanoljaPage/IntroPage/IntroPage.tsx
  src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
  src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.tsx
  src/pages/myPage/MyPage.tsx
  src/pages/myPage/info/Info.tsx
  src/pages/myPage/manage/Manage.tsx
  src/pages/notFoundPage/index.tsx
  src/pages/purchaseDetailPage/PurchaseDetail.style.ts
  src/pages/purchaseDetailPage/PurchaseDetail.tsx
  src/pages/roomDetailPage/RoomDetail.tsx
  src/pages/saleDetailPage/SaleDetail.tsx
  src/pages/searchPage/Search.tsx
  src/pages/searchPage/components/searchItem/SearchItem.style.ts
  src/pages/searchPage/components/searchItem/SearchItem.tsx
  src/pages/signInPage/SignIn.tsx
  src/pages/transferPurchasePage/TransferPurchase.tsx
  src/pages/transferPurchasePage/components/puchaseItem/PuchaseItem.style.ts
  src/pages/transferPurchasePage/components/puchaseItem/PuchaseItem.tsx
  src/pages/transferSalePage/TransferSale.tsx
  src/pages/transferWritingPage/TransferWriting.tsx
  src/pages/transferWritingPage/transferItem/TransferItem.style.ts
  src/pages/transferWritingPage/transferItem/TransferItem.tsx
  src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx
  src/routes/router.tsx
  src/store/store.ts
  src/utils/getNotificationPermission.ts
Labels: FIX

#313 [#312]리드미 추가작성
  README.md
Labels: CHORE

#315 [#275] path가 바뀔 때마다 토스트 상태 리셋
  src/App.tsx
  src/components/toast/Toast.tsx
  src/pages/paymentPage/Payment.tsx
  src/store/store.ts
Labels: FIX

#318 [#317] 로그인/회원가입 e2e 테스트
  .gitignore
  playwright.config.ts
  tests/e2eTests/example.spec.ts
  tests/e2eTests/global.setup.ts
  tests/e2eTests/models/LoginPage.ts
  tests/e2eTests/models/SignupPage.ts
  tests/e2eTests/specs/authentication/login.spec.ts
  tests/e2eTests/specs/authentication/register.spec.ts
  tests/unitTestsSrc/VerificationPage.spec.tsx
  tests/unitTestsSrc/useEmailVerification.spec.tsx
  tsconfig.json
  vite.config.ts
Labels: TEST
